FROM php:7.3-cli

# Consigure users to match host users
ARG USER_ID
ARG GROUP_ID

RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    groupadd -g ${GROUP_ID} user &&\
    useradd -l -u ${USER_ID} -g ${GROUP_ID} user &&\
    install -d -m 0755 -o user -g user /home/user \
;fi

# Install the deps
RUN apt-get update \
    && pecl install igbinary \
    && pecl install ast \
    && pecl install xdebug \
    && apt-get install -y git \
    && yes no | pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-enable ast \
    && docker-php-ext-enable igbinary \
    && docker-php-ext-enable xdebug

WORKDIR /home/user

# Add PHP Code Sniffer, PHP Mess Detector, Phan
RUN curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
RUN curl -OL https://github.com/phpmd/phpmd/releases/download/2.7.0/phpmd.phar
RUN curl -OL https://github.com/phan/phan/releases/download/2.2.11/phan.phar

RUN chown -R user:user /home/user

# Configuration
ENV PHAN_ALLOW_XDEBUG 1
ENV PHAN_DISABLE_XDEBUG_WARN 1

# Permissions
RUN mkdir /app
RUN chown -R user:user /app

WORKDIR /app

CMD su user -s /bin/bash -c /app/tests.sh
